version: "3.1"
services:

    redis:
      image: redis:4
      ports:
        - "6379:6379"
      container_name: termPortal-redis

    redis_web_manager:
      image: marian/rebrow
      container_name: redis-ui
      ports:
        - "5001:5001"
    node:
      image: node:8.11.1
      container_name: termPortal-node
      stdin_open: true
      tty: true
      ports:
       - "80:8081"
      volumes:
       - ./src/:/usr/src/app/
      environment:
       - NODE_ENV=dev